# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  run-tests:
    parameters:
      python-version:
        type: string
    docker: [image: circleci/python:<<parameters.python-version>>]
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: make setup
      - run:
          name: run tests
          command: make test

workflows:
  build:
    jobs:
      - run-tests:
          matrix:
            parameters:
              python-version:
                - 3.6.8
                - 3.7.5
                - 3.8.0
